- common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java
- container-managed/pom.xml
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedContainerConfiguration.java
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/ThreadContextClassloaderTest.java
- container-managed/src/test/resources/arquillian.xml
- pom.xml
- protocol-jmx/src/main/java/org/jboss/as/arquillian/protocol/jmx/ArquillianServiceDeployer.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/protocol/jmx/ExtendedJMXProtocol.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/protocol/jmx/ExtendedJMXProtocolConfiguration.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/protocol/jmx/JMXProtocolPackager.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianService.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ContextManager.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ContextManagerBuilder.java
https://issues.jboss.org/browse/WFLY-4392
> [WFLY-4392] Make use of TCCL in ARQ ManagedContainer configurable

- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- common/src/main/java/org/jboss/as/arquillian/container/ManagementClient.java
> Change the ManagementClient to initialize itself internally

- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- common/src/main/java/org/jboss/as/arquillian/container/ContainerDescription.java
- common/src/main/java/org/jboss/as/arquillian/container/StandardContainerDescription.java
@ctomc Would you remind reviewing this?
> Add information about the running container.

- common/src/main/java/org/jboss/as/arquillian/api/WildFlyContainerController.java
- common/src/main/java/org/jboss/as/arquillian/container/CommonContainerExtension.java
- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/StopContainerWithTimeout.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/WildFlyClientContainerController.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/WildFlyClientContainerControllerCreator.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/WildFlyClientContainerControllerProvider.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/WildFlyContainerContainerController.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/WildFlyContainerContainerControllerCreator.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/WildFlyContainerContainerControllerProvider.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/WildFlyContainerControllerArquillianDeploymentAppender.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/WildFlyContainerControllerRemoteExtension.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/WildFlyContainerLifecycleController.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/command/StopWithTimeoutContainerCommand.java
- common/src/main/java/org/jboss/as/arquillian/container/controller/command/WildFlyContainerCommandObserver.java
- common/src/main/resources/META-INF/services/org.jboss.arquillian.spi.client.deployment.AuxiliaryArchiveAppender
- container-embedded/src/main/java/org/jboss/as/arquillian/container/embedded/EmbeddedDeployableContainer.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
- container-remote/src/main/java/org/jboss/as/arquillian/container/remote/RemoteDeployableContainer.java
- pom.xml
Allow Arquillian to specify a timeout value for the WildFly clean shutdown mechanism when shutting down a server
~~Also needs to incorporate update arquillian-core to 1.1.6.Final to pick up few changes.~~
> WFLY-4255 [master]

- pom.xml
https://issues.jboss.org/browse/ARQ-1992
> [master] Upgrade arquillian to address ARQ-1992

- common/src/main/java/org/jboss/as/arquillian/api/ServerSetup.java
Allow server setup to be inherited in base class, applied to sub class.
> #51 Mark ServerSetup as inherited.

- protocol-jmx/src/main/java/org/jboss/as/arquillian/protocol/jmx/JMXProtocolPackager.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianConfig.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianConfigServiceCustomizer.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianService.java
> WFARQ-12 Allow extending ArquillianConfig service (against 2.0 master)

- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianConfig.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianConfigBuilder.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianService.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ContextManager.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/InContainerManagementClientProvider.java
- testenricher-msc/src/main/java/org/jboss/arquillian/testenricher/msc/ServiceTargetAssociation.java
- testenricher-msc/src/main/java/org/jboss/arquillian/testenricher/msc/ServiceTargetProvider.java
Also cleanup how arquillian services are created and use injection instead of params in constructor.
> JBEAP-7598 Fix memory leak in JMX protocol

- container-managed/pom.xml
- pom.xml
- testng-integration/src/test/resources/arquillian.xml
- setup/teardown actions are not called on @Ignore tests
- deployments are not created / deployed on @Ignore tes
> Upgrade Arquillian core and related deps

- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
https://issues.jboss.org/browse/WFARQ-37
> [WFARQ-37] Only log the bundles warning if the property is defined.

- common/src/main/java/org/jboss/as/arquillian/container/ServerSetupObserver.java
https://issues.jboss.org/browse/WFARQ-39
> [WFARQ-39] catching AssertionError from SetupTask.tearDown

- pom.xml
https://issues.jboss.org/browse/WFARQ-42
> [WFARQ-42] Upgrade WildFly Core from 3.0.9.Final to 4.0.0.Final.

- pom.xml
JIRA - https://issues.jboss.org/browse/WFARQ-40
> WFARQ-40 Upgrade Arquillian core to 1.4.0.Final.

- container-managed-domain/src/main/java/org/jboss/as/arquillian/container/domain/managed/ManagedDomainDeployableContainer.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
https://issues.jboss.org/browse/WFARQ-44
> WFARQ-44 switch order while StandaloneCommandBuilder is built

- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- container-managed-domain/src/main/java/org/jboss/as/arquillian/container/domain/managed/ManagedDomainDeployableContainer.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
https://issues.jboss.org/browse/WFARQ-51
> [WFARQ-51] modulePath without WILDFLY_HOME/modules, NPE fix

- common-domain/src/main/java/org/jboss/as/arquillian/container/domain/ManagementClient.java
- container-embedded/pom.xml
- container-managed-domain/pom.xml
- pom.xml
https://issues.jboss.org/browse/WFARQ-48
https://issues.jboss.org/browse/WFARQ-49
https://issues.jboss.org/browse/WFARQ-52
> Get the build and runtime to work with Java 11

- pom.xml
https://issues.jboss.org/browse/WFARQ-57
> [WFARQ-57] Upgrade wildfly-core from 7.0.0.Final to 8.0.0.Final.

- pom.xml
Reverts wildfly/wildfly-arquillian#153
Looks like this is required.
> Revert "[WFARQ-58] Remove the JBoss Maven Repository entry. Also use an https…"

- pom.xml
https://issues.jboss.org/browse/WFARQ-58
> [WFARQ-58] Use secure connections for JBoss Repositories.

- common-domain/pom.xml
- container-embedded/pom.xml
- container-managed-domain/pom.xml
- container-managed/pom.xml
- container-remote-domain/pom.xml
- container-remote/pom.xml
- integration-tests/elytron/domain/pom.xml
- integration-tests/elytron/standalone/pom.xml
- pom.xml
https://issues.redhat.com/browse/WFARQ-61
https://issues.redhat.com/browse/WFARQ-62
> Upgrade core and migrate Java EE components to Jakarta EE

- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedContainerConfiguration.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/manual/ReadOnlyServerConfigTestCase.java
- container-managed/src/test/resources/manual-arquillian.xml
https://issues.redhat.com/browse/WFARQ-75
> [WFARQ-75] Add an explicit read only server configuration option.

- README.adoc
- pom.xml
https://issues.redhat.com/browse/WFARQ-76
> Add a README and require a minimum of Maven 3.6.0.

- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- common/src/main/java/org/jboss/as/arquillian/container/CommonManagedDeployableContainer.java
… There is a chance stop may be called outside the container context scope resulting in an NPE with the ManagementClient producer.
https://issues.redhat.com/browse/WFARQ-47
> [WFARQ-47] Store a ManagementClient instance instead of using the producer to get the client.

- pom.xml
https://issues.redhat.com/browse/WFARQ-82
> [WFARQ-82] Upgrade WildFly Core to 13.0.0.Beta6.

- pom.xml
https://issues.redhat.com/browse/WFARQ-64
> [WFARQ-64] Upgrade WildFly Core to 13.0.0.Final.

- pom.xml
https://issues.redhat.com/browse/WFARQ-88
> [WFARQ-88] Upgrade Arquillian to 1.7.0.Alpha6

- container-bootable/pom.xml
- pom.xml
https://issues.redhat.com/browse/WFARQ-90
https://issues.redhat.com/browse/WFARQ-91
> WildFly Component Upgrades

- container-embedded/src/test/java/org/jboss/as/arquillian/container/embedded/SystemPropertyServiceActivator.java
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/SystemPropertyServiceActivator.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianConfig.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianConfigBuilder.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianService.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ContextManager.java
This is temporary solution until better one will be available:
* https://issues.redhat.com/browse/WFARQ-50 - migrates to new API
* https://issues.redhat.com/browse/WFARQ-84 - fixes identified regression after migration
> Migrate MSC to new API where possible

- common-domain/pom.xml
- common/pom.xml
- container-bootable/pom.xml
- container-embedded/pom.xml
- container-managed-domain/pom.xml
- container-managed/pom.xml
- container-remote-domain/pom.xml
- container-remote/pom.xml
- integration-tests/elytron/pom.xml
- integration-tests/junit5-tests/pom.xml
- integration-tests/junit5-tests/src/test/java/org/wildfly/arquillian/integration/test/junit5/ClientTestCase.java
- integration-tests/junit5-tests/src/test/java/org/wildfly/arquillian/integration/test/junit5/Greeter.java
- integration-tests/junit5-tests/src/test/java/org/wildfly/arquillian/integration/test/junit5/GreeterServlet.java
- integration-tests/junit5-tests/src/test/java/org/wildfly/arquillian/integration/test/junit5/InContainerTestCase.java
- integration-tests/junit5-tests/src/test/resources/arquillian.xml
- integration-tests/pom.xml
- pom.xml
- protocol-jmx/pom.xml
- protocol-jmx/src/main/java/org/jboss/as/arquillian/protocol/jmx/JMXProtocolPackager.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianConfigBuilder.java
https://issues.redhat.com/browse/WFARQ-85
> [WFARQ-85] Initial testing for JUnit 5 support.

- common-domain/pom.xml
- container-bootable/pom.xml
- container-managed-domain/pom.xml
- container-managed/pom.xml
- container-remote-domain/pom.xml
- container-remote/pom.xml
- integration-tests/elytron/domain/pom.xml
- integration-tests/elytron/standalone/pom.xml
- integration-tests/junit5-tests/pom.xml
- pom.xml
- https://issues.redhat.com/browse/WFARQ-93
- https://issues.redhat.com/browse/WFARQ-94
- https://issues.redhat.com/browse/WFARQ-95
- https://issues.redhat.com/browse/WFARQ-96
- https://issues.redhat.com/browse/WFARQ-97
> Component upgrades and tasks

- container-bootable/pom.xml
- pom.xml
https://issues.redhat.com/browse/WFARQ-101
> [WFARQ-101] Upgrade the wildfly-jar-maven-plugin to 6.1.1.Final.

- pom.xml
* https://issues.redhat.com/browse/WFARQ-105
* https://issues.redhat.com/browse/WFARQ-106
* https://issues.redhat.com/browse/WFARQ-107
* https://issues.redhat.com/browse/WFARQ-108
* https://issues.redhat.com/browse/WFARQ-109
Upstream: #207
> Component upgrades 4.x

- container-bootable/pom.xml
- container-bootable/src/test/java/org/jboss/as/arquillian/container/managed/archive/GreetingService.java
- container-embedded/src/test/java/org/jboss/as/arquillian/container/embedded/archive/GreetingService.java
- container-managed/pom.xml
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/archive/GreetingService.java
- container-remote/pom.xml
- container-remote/src/test/java/org/jboss/as/arquillian/container/remote/archive/GreetingService.java
- integration-tests/junit5-tests/pom.xml
- integration-tests/junit5-tests/src/test/java/org/wildfly/arquillian/integration/test/junit5/ClientTestCase.java
- integration-tests/junit5-tests/src/test/java/org/wildfly/arquillian/integration/test/junit5/Greeter.java
- pom.xml
Use bean defining annotations and minor fix to allow skipping of provisioning.
> Test fixes

- pom.xml
https://issues.redhat.com/browse/WFARQ-110
> WFARQ-110 Upgrade jakarta.ejb-api from 4.0.0 to 4.0.1

- pom.xml
https://issues.redhat.com/browse/WFARQ-113
> [WFARQ-113] Upgrade Arquillian to 1.7.0.Alpha11.

- integration-tests/elytron/standalone/pom.xml
- pom.xml
> Enable the maven-release-plugin.

- pom.xml
https://issues.redhat.com/browse/WFARQ-116
Upstream: #224
> [WFARQ-116] Upgrade Arquillian to 1.7.0.Alpha12.

- common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java
- common/src/main/java/org/jboss/as/arquillian/container/ManagementClient.java
- integration-tests/junit5-tests/src/test/resources/override-web-uri-arquillian.xml
https://issues.redhat.com/browse/WFARQ-121
> [WFARQ-121] Rename the socketBindingGroup property to socketBindingName.

- .github/workflows/maven.yml
- .github/workflows/wildfly-build.yml
- container-bootable/pom.xml
- pom.xml
- testng-integration/pom.xml
- testng-integration/src/test/java/org/jboss/as/arquillian/testng/BasicTestNGIntegrationTestCase.java
Component upgrades and testing with WildFly 26 and 27.
- https://issues.redhat.com/browse/WFARQ-127
- https://issues.redhat.com/browse/WFARQ-128
- https://issues.redhat.com/browse/WFARQ-122
> Component upgrades for several components

- integration-tests/domain/pom.xml
- integration-tests/domain/src/test/java/org/wildfly/arquillian/integration/test/domain/config/WarClientOverrideWebUriTestCase.java
- integration-tests/junit5-tests/pom.xml
- integration-tests/junit5-tests/src/test/java/org/wildfly/arquillian/integration/test/junit5/ClientTestCase.java
- integration-tests/junit5-tests/src/test/java/org/wildfly/arquillian/integration/test/junit5/config/WarClientOverrideWebUriTestCase.java
- pom.xml
https://issues.redhat.com/browse/WFARQ-130
> [WFARQ-130] Remove the dependency on OkHttp.

- common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java
- container-bootable/src/main/java/org/jboss/as/arquillian/container/bootable/BootableDeployableContainer.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
* Creating a new yamlConfiguration parameter
Jira: https://issues.redhat.com/browse/WFARQ-135
> [WFARQ-135]: Add support for yaml extension files.

- common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java
- container-managed/pom.xml
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedContainerConfiguration.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/manual/YamlConfigTestCase.java
- container-managed/src/test/resources/manual-arquillian.xml
- container-managed/src/test/resources/test-config-1.yml
- container-managed/src/test/resources/test-config-2.yml
https://issues.redhat.com/browse/WFARQ-135
> [WFARQ-135] Follow up with test and move the configuration settings

- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedContainerConfiguration.java
- pom.xml
> Upgrade and backport

- container-bootable/src/main/java/org/jboss/as/arquillian/container/bootable/BootableContainerConfiguration.java
- container-bootable/src/main/java/org/jboss/as/arquillian/container/bootable/BootableDeployableContainer.java
- container-bootable/src/test/java/org/jboss/as/arquillian/container/managed/manual/DebugManualModeTestCase.java
- container-bootable/src/test/resources/manual-arquillian.xml
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedContainerConfiguration.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/manual/DebugManualModeTestCase.java
- container-managed/src/test/resources/manual-arquillian.xml
- pom.xml
https://issues.redhat.com/browse/WFARQ-142
> [WFARQ-142] Add support for launching the server in debug mode.

- common-domain/src/main/java/org/wildfly/arquillian/domain/container/controller/ClientDomainContainerController.java
- container-bootable/src/test/java/org/jboss/as/arquillian/container/managed/manual/AbstractManualModeTestCase.java
- container-bootable/src/test/java/org/jboss/as/arquillian/container/managed/manual/ClientManualModeTestCase.java
- container-bootable/src/test/java/org/jboss/as/arquillian/container/managed/manual/InContainerManualModeTestCase.java
- container-bootable/src/test/resources/arquillian.xml
- container-bootable/src/test/resources/manual-arquillian.xml
- container-managed-domain/src/main/java/org/jboss/as/arquillian/container/domain/managed/ManagedDomainDeployableContainer.java
- container-managed-domain/src/test/java/org/jboss/as/arquillian/container/domain/managed/test/AbstractDomainManualModeTestCase.java
- container-managed-domain/src/test/java/org/jboss/as/arquillian/container/domain/managed/test/DomainManualModeClientTestCase.java
- container-managed-domain/src/test/java/org/jboss/as/arquillian/container/domain/managed/test/DomainManualModeInContainerTestCase.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/manual/AbstractManualModeTestCase.java
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/manual/ClientManualModeTestCase.java
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/manual/InContainerManualModeTestCase.java
- container-managed/src/test/resources/arquillian.xml
- container-managed/src/test/resources/manual-arquillian.xml
Fixing this revealed other bugs that were also fixed in this PR.
* https://issues.redhat.com/browse/WFARQ-144
* https://issues.redhat.com/browse/WFARQ-145
* https://issues.redhat.com/browse/WFARQ-146
> Fix the in container tests to ensure they run in a container

- pom.xml
- protocol-jmx/pom.xml
https://issues.redhat.com/browse/WFARA-156
> [WFARQ=156] Migrate to SmallRye Jandex.

- junit-api/src/main/java/org/wildfly/arquillian/junit/condition/RequiresModuleExecutionCondition.java
- junit-api/src/test/resources/fake-modules/modules/org/wildfly/arquillian/junit/test/resource-root/main/module.xml
https://issues.redhat.com/browse/WFARQ-164
> [WFARQ-164] Validate the module name from the module.xml file.

- bom/project-bom/pom.xml
https://issues.redhat.com/browse/WFARQ-191
> [WFARQ-191] Upgrade the JBoss EJB Client to 5.0.7.Final.

- bom/project-bom/pom.xml
https://issues.redhat.com/browse/WFARQ-205
> [WFARQ-205] Upgrade wildfly-launcher to 1.0.2.Final.

- bom/project-bom/pom.xml
- container-remote/src/test/java/org/jboss/as/arquillian/container/remote/ServletClientTestCase.java
https://issues.redhat.com/browse/WFARQ-209
> [WFARQ-209] Upgrade Arquillian to 1.9.5.Final.
