- common-domain/pom.xml
- common-domain/src/main/java/org/jboss/as/arquillian/container/domain/ServerGroupContainer.java
- common/pom.xml
- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- container-embedded/embedded-server-provisioning.xml
- container-embedded/pom.xml
- container-embedded/src/main/java/org/jboss/as/arquillian/container/embedded/EmbeddedContainerConfiguration.java
- container-embedded/src/main/java/org/jboss/as/arquillian/container/embedded/EmbeddedDeployableContainer.java
- container-embedded/src/test/java/org/jboss/as/arquillian/container/embedded/EmbeddedContainerConfigurationTestCase.java
- container-managed-domain/pom.xml
- container-managed-domain/src/main/java/org/jboss/as/arquillian/container/domain/managed/ManagedDomainDeployableContainer.java
- container-managed/pom.xml
- container-remote-domain/pom.xml
- container-remote/pom.xml
- pom.xml
- protocol-jmx/pom.xml
- server-provisioning.xml
- testenricher-msc/pom.xml
- testng-integration/pom.xml
Also change the way we do testing with usage of provisioning plugin & feature-packs
should address https://issues.jboss.org/browse/WFLY-4572
> Upgrade to wildfly CR2, re-add embedded, remove common-core dep

- common/pom.xml
- common/src/main/java/org/jboss/as/arquillian/container/ManagementClient.java
- common/src/test/java/org/jboss/as/arquillian/container/ManagementClientTest.java
I couldn't come up with a better test case because of some structural issues.
- This bug only replicates when protocol == servlet, but all of these tests run as JMX.
- Switching to the servlet protocol didn't work, i'm not sure if there are classpath issues or what.  Need to look at the logs closer.
- Creating a dedicated module to test this didn't make much sense either.
> WFARQ-4 When reading IP address, if its 0.0.0.0 convert to 127.0.0.1.

- container-embedded/src/main/java/org/jboss/as/arquillian/container/embedded/EmbeddedContainerConfiguration.java
- container-embedded/src/main/java/org/jboss/as/arquillian/container/embedded/EmbeddedDeployableContainer.java
I don't know exactly how to test if JBoss Modules is picking up "jboss.modules.system.pkgs", i tested just running with the coverage agent from IntelliJ IDEA. Before patching with this code, it was not possible, see here: https://stackoverflow.com/questions/37463876/coverage-integration-tests-intellij-on-wildfly
> Adding "jboss.modules.system.pkgs" to embedded configuration.

- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
- pom.xml
Improves error message when port is in use. Previous one was assuming that the server is running and managed containers by default should not connect to running instances. It might be however, that the default port 9990 is taken by some other process - for example [NVidia updater](http://in.relation.to/2016/07/28/how-to-fix-arquillian-and-nvidia-port-stealing-issue/) ;)
This pull request changes the error message with a bit more information of what might be happening.
As a bonus - update to latest Arquillian Core :)
> Improves error message when mgmt port is in use

- common/src/main/java/org/jboss/as/arquillian/container/ServerSetupObserver.java
Jira
https://issues.jboss.org/browse/WFARQ-14
* handleOnUndeploy not counting with the possibility of undeploy being fired by arq-core
> WFARQ-14 NPE in ServerSetupObserver.handleAfterUndeploy

- common-domain/src/main/java/org/jboss/as/arquillian/container/domain/CommonDomainContainerConfiguration.java
- common-domain/src/main/java/org/jboss/as/arquillian/container/domain/CommonDomainDeployableContainer.java
- common/pom.xml
- common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java
- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- common/src/main/java/org/jboss/as/arquillian/container/ContextualJMXConnectorFactory.java
- common/src/main/java/org/jboss/as/arquillian/container/ManagementClient.java
- container-managed-domain/pom.xml
- integration-tests/elytron/domain/pom.xml
- integration-tests/elytron/domain/src/test/java/org/wildfly/arquillian/integration/test/domain/ElytronIntegrationTestCase.java
- integration-tests/elytron/domain/src/test/resources/arquillian.xml
- integration-tests/elytron/domain/src/test/resources/elytron-wildfly-config.xml
- integration-tests/elytron/pom.xml
- integration-tests/elytron/server-provisioning.xml
- integration-tests/elytron/standalone/pom.xml
- integration-tests/elytron/standalone/src/test/java/org/wildfly/arquillian/integration/test/standalone/ElytronIntegrationTestCase.java
- integration-tests/elytron/standalone/src/test/resources/arquillian.xml
- integration-tests/elytron/standalone/src/test/resources/elytron-wildfly-config.xml
- integration-tests/pom.xml
- pom.xml
- protocol-jmx/src/main/java/org/jboss/as/arquillian/protocol/jmx/ArquillianServiceDeployer.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/protocol/jmx/JMXProtocolPackager.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/InContainerManagementClientProvider.java
First commit adds the Elytron support. 
Second commit adds some tests for the Elytron support. These tests aren't required and they do add a new integration-tests Maven module. I'm not sure if we should do this or not, but there have been times where integration tests would likely catch some errors.
> [WFARQ-20] Add Elytron support

- common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java
- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- common/src/main/java/org/jboss/as/arquillian/container/ManagementClient.java
Fixes https://issues.jboss.org/browse/WFARQ-30
Now you can use following configuration in arquillian.xml to override host if wildfly is binded to `0.0.0.0` so you can run test as `@RunAsClient`
```xml
<container qualifier="remote-container" default="true">
<configuration>
<property name="managementPort">9991</property>
<property name="host">192.168.165.37</property>
<property name="port">8097</property>
</configuration>
</container>
```
> Overriding property `host` & `port` from arquillian configuration if wildfly is binded to 0.0.0.0

- common/src/main/java/org/jboss/as/arquillian/container/ServerSetupObserver.java
https://issues.jboss.org/browse/WFARQ-39
Resolves problem when failed tearDown causes following unrelated testcase failure.
When management operation in tearDown fails, AssertionError is thrown, but ServerSetupObserver catch only Exceptions - processing of setup tasks of following test is skipped and unrelated test fails.
> [WFARQ-39] catching AssertionError from SetupTask.tearDown

- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- container-managed-domain/src/main/java/org/jboss/as/arquillian/container/domain/managed/ManagedDomainDeployableContainer.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
https://issues.jboss.org/browse/WFARQ-51
* modulePath arquillian property should override module.path passed into the server, default WILDFLY_HOME/modules should be removed (causes Duplicate layer 'base' warnings, only one place in wildfly testsuite where this is used - and there is the Duplicate layer warning to fix too - see https://issues.jboss.org/browse/WFLY-10631)
* fixed minor NPE visible in the same log
~When this will be fixed, fix of https://issues.jboss.org/browse/WFLY-10631 will be required in wildfly to not break the tests on upgrade.~
> [WFARQ-51] modulePath without WILDFLY_HOME/modules, NPE fix

- container-managed-domain/src/main/java/org/jboss/as/arquillian/container/domain/managed/ManagedDomainDeployableContainer.java
- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java
https://issues.jboss.org/browse/WFARQ-51
> [WFARQ-51] modulePath without WILDFLY_HOME/modules

- container-embedded/pom.xml
- container-managed-domain/pom.xml
- container-managed/pom.xml
- integration-tests/elytron/domain/pom.xml
- integration-tests/elytron/standalone/pom.xml
- testng-integration/pom.xml
I encountered some issues running the tests on a development system where the `JBOSS_HOME` environment variable was set to a local installation of WildFly running at an other version. As the tests are ran against a local JBOSS_HOME anyway, it probably makes sense to override any present  `JBOSS_HOME` variable with the provided folder for the tests.
> Set JBOSS_HOME environment variable

- common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java
- common/src/main/java/org/jboss/as/arquillian/container/CommonDeployableContainer.java
- Closes https://issues.redhat.com/browse/WFARQ-3?_sscc=t
> Optional connectionTimeout property support added

- container-embedded/src/test/java/org/jboss/as/arquillian/container/embedded/SystemPropertyServiceActivator.java
- container-managed/src/test/java/org/jboss/as/arquillian/container/managed/SystemPropertyServiceActivator.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianConfig.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianConfigBuilder.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ArquillianService.java
- protocol-jmx/src/main/java/org/jboss/as/arquillian/service/ContextManager.java
Reverts wildfly/wildfly-arquillian#140
See https://issues.redhat.com/browse/WFARQ-84 for details. I think we need to take a better look at this as it's causing failures in WildFly. WildFly itself has downgraded back to WFARQ 2.2, https://github.com/wildfly/wildfly/pull/13636.
> Revert "A couple of JBoss MSC API deprecation fixes"

- common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java
- common/src/main/java/org/jboss/as/arquillian/container/ManagementClient.java
- integration-tests/junit5-tests/src/test/resources/override-web-uri-arquillian.xml
https://issues.redhat.com/browse/WFARQ-121
> [WFARQ-121] Rename the socketBindingGroup property to socketBindingName.

- .github/workflows/maven.yml
- pom.xml
https://issues.redhat.com/browse/WFARQ-124
> [WFARQ-124] Require a minimum of Java 11 for runtime.

- container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedContainerConfiguration.java
After this change to Wildfly core
https://github.com/wildfly/wildfly-core/commit/a958b5e1f000b4db8b8da2ec38e85fe850a0d9ec
Driven by this issue
https://issues.redhat.com/browse/WFCORE-5792
A server config file that is stored outside of the managed Wildfly server's configuration directory can no longer be provided via the jboss.server.config.file.name system property.  A read-only server config must be used if the config file is outside the configuration directory.
This is problematic if, for example, one keeps a test server config file under version control in a project's test resources directory while having the managed Wildfly instance outside of the code base, and one wants to continue to utilize system properties to set the server config. Setting the server config, regardless of …
> Add system property for setting read only server config

- junit-api/src/main/java/org/wildfly/arquillian/junit/condition/RequiresModuleExecutionCondition.java
- junit-api/src/test/java/org/wildfly/arquillian/junit/requires/module/RequireSnapshot.java
- junit-api/src/test/java/org/wildfly/arquillian/junit/requires/module/RequiresModuleTestCase.java
- junit-api/src/test/resources/fake-modules/modules/org/wildfly/arquillian/junit/test/snapshot/main/module.xml
- pom.xml
Note this also requires an upgrade to the wildfly-plugin-tools.
- https://issues.redhat.com/browse/WFARQ-162
- https://issues.redhat.com/browse/WFARQ-163
> [WFARQ-162] Ignore the SNAPSHOT qualifier when comparing versions

- common/src/main/java/org/jboss/as/arquillian/api/ReloadIfRequired.java
- common/src/main/java/org/jboss/as/arquillian/container/ServerSetupObserver.java
- integration-tests/junit5-tests/src/test/java/org/wildfly/arquillian/integration/test/junit5/server/setup/ReloadIfRequiredAnnotationTestCase.java
https://issues.redhat.com/browse/WFARQ-185
> [WFARQ-185] Add a ReloadIfRequired annotation for ServerSetupTask's.

- bom/project-bom/pom.xml
- common/pom.xml
- container-bootable/pom.xml
- container-managed-domain/pom.xml
- container-managed/pom.xml
https://issues.redhat.com/browse/WFARQ-196
> [WFARQ-196] Migrate to using the new WildFly Launcher API GAV.

- common-domain/pom.xml
- common/pom.xml
Fixes https://issues.redhat.com/browse/WFARQ-207
> WFARQ-207 Remote container: NoSuchMethodError:'Logger.getMessageLogger'
